package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// 配置结构体
type Config struct {
	InputFile  string
	OutputFile string
}

func main() {
	// 1. 定义命令行参数
	// usage 是帮助信息
	inputFile := flag.String("input", "", "必填。Go 源文件路径 (例如: ./backend/events.go)")
	outputFile := flag.String("output", "", "必填。输出的 TS 文件路径 (例如: ./frontend/src/events.gen.ts)")

	// 解析参数
	flag.Parse()

	// 2. 校验必填参数
	if *inputFile == "" || *outputFile == "" {
		fmt.Println("❌ 错误: 必须指定 -input 和 -output 参数")
		flag.Usage()
		os.Exit(1)
	}

	// 3. 转换为绝对路径 (解决相对路径在不同目录运行找不到文件的问题)
	absInput, err := filepath.Abs(*inputFile)
	if err != nil {
		fmt.Printf("❌ 解析输入路径失败: %v\n", err)
		os.Exit(1)
	}

	absOutput, err := filepath.Abs(*outputFile)
	if err != nil {
		fmt.Printf("❌ 解析输出路径失败: %v\n", err)
		os.Exit(1)
	}

	cfg := Config{
		InputFile:  absInput,
		OutputFile: absOutput,
	}

	// 4. 执行生成
	err = generate(cfg)
	if err != nil {
		fmt.Printf("❌ 生成失败: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("✅ 成功生成: %s\n", cfg.OutputFile)
}

// generate 核心生成逻辑
func generate(cfg Config) error {
	// 检查输入文件是否存在
	if _, err := os.Stat(cfg.InputFile); os.IsNotExist(err) {
		return fmt.Errorf("输入文件不存在: %s", cfg.InputFile)
	}

	// 解析 Go 文件
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, cfg.InputFile, nil, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("解析 Go 文件失败: %w", err)
	}

	constants := []EventConstant{}

	// 遍历 AST
	for _, decl := range node.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok || genDecl.Tok != token.CONST {
			continue
		}

		for _, spec := range genDecl.Specs {
			vSpec := spec.(*ast.ValueSpec)
			for i, name := range vSpec.Names {
				var val string
				if vSpec.Values != nil && i < len(vSpec.Values) {
					if bl, ok := vSpec.Values[i].(*ast.BasicLit); ok {
						val = bl.Value
					}
				}

				if name.Name != "" && val != "" {
					constants = append(constants, EventConstant{
						Name:  name.Name,
						Value: strings.Trim(val, `"`),
					})
				}
			}
		}
	}

	// 模板渲染
	tmplText := `// Code generated by gents; DO NOT EDIT.
/* eslint-disable */
export const Events = {
{{- range . }}
  {{ .Name }}: {{ .Value | quote }},
{{- end }}
} as const;

export type EventName = typeof Events[keyof typeof Events];
`

	funcMap := template.FuncMap{
		"quote": func(s string) string {
			return fmt.Sprintf(`"%s"`, s)
		},
	}

	t := template.Must(template.New("ts").Funcs(funcMap).Parse(tmplText))

	// 确保输出目录存在
	outputDir := filepath.Dir(cfg.OutputFile)
	if err := os.MkdirAll(outputDir, 0755); err != nil {
		return fmt.Errorf("创建输出目录失败: %w", err)
	}

	outFile, err := os.Create(cfg.OutputFile)
	if err != nil {
		return fmt.Errorf("创建输出文件失败: %w", err)
	}
	defer outFile.Close()

	err = t.Execute(outFile, constants)
	if err != nil {
		return fmt.Errorf("渲染模板失败: %w", err)
	}

	return nil
}

type EventConstant struct {
	Name  string
	Value string
}
