// Code generated by gents; DO NOT EDIT.
/* eslint-disable */
export const Events = {
  EventAppReady: "app:ready",
  EventAppClose: "app:close",
  EventDataUpdate: "data:update",
  EventUserLogin: "user:login",
} as const;

export type EventName = typeof Events[keyof typeof Events];
