// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecsRename() {
  return window['go']['main']['App']['ExecsRename']();
}

export function GetPreview() {
  return window['go']['main']['App']['GetPreview']();
}

export function GetRules() {
  return window['go']['main']['App']['GetRules']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenDirectoryDialog() {
  return window['go']['main']['App']['OpenDirectoryDialog']();
}

export function OpenInFinder(arg1) {
  return window['go']['main']['App']['OpenInFinder'](arg1);
}

export function OpenMultipleFilesDialog() {
  return window['go']['main']['App']['OpenMultipleFilesDialog']();
}

export function SetRules(arg1) {
  return window['go']['main']['App']['SetRules'](arg1);
}
