// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExecsRename():Promise<void>;

export function GetPreview():Promise<Array<main.RenamePreview>>;

export function GetRules():Promise<main.Rules>;

export function Greet(arg1:string):Promise<string>;

export function OpenDirectoryDialog():Promise<void>;

export function OpenInFinder(arg1:string):Promise<void>;

export function OpenMultipleFilesDialog():Promise<void>;

export function SetRules(arg1:main.Rules):Promise<void>;
